### ISSUE TITLE
Allow receiver to check how many producers their are

### ISSUE THREAD

**Issue by insanitybit** [stjepang/channel#1]
It would be helpful if there were a way to see the actual reference count rather than just if there are any producers.

**Comment by stjepang** [comment]
Out of curiosity, do you have an example of where you would find this feature useful?

**Comment by insanitybit** [comment]
Honestly, I think I was probably solving the problem the wrong way around. But I knew in my system that there would be a cycle (the receiver struct had a reference to the sender), so I couldn't rely on the typical closing behavior when all senders are dropped. I wanted to check for 1 producer and then perform my 'exit' actions.

**Comment by stjepang** [comment]
Closing the issue. If you still need this feature, let me know.
